[tool.poetry]
name = "itvArith"
version = "0.1.0"
description = ""
authors = ["iopi <lionel.auroux@gmail.com>"]
packages = [{include = "itvArith"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
